on:
  create:
    ref_type: tag
name: Automatic release

jobs:
  release-target:
    if: github.event.ref_type == 'tag'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            ext: ""
          - os: windows-latest
            platform: win64
            ext: .exe
          - os: macos-latest
            platform: macos
            ext: .bin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetching branch
        uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Compile macOS source
        if: matrix.platform == 'macos'
        run: pyinstaller index.py --onefile --icon=assets/logo.icns --name target${{ matrix.ext }}
      - name: Compile Linux source
        if: matrix.platform == 'linux'
        run: pyinstaller index.py --onefile --icon=assets/logo.ico --name target${{ matrix.ext }}
      - name: Compile win64 source
        if: matrix.platform == 'win64'
        run: nuitka --follow-imports --onefile index.py --windows-icon-from-ico="./assets/logo.ico" -o target${{ matrix.ext }}
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: GiveMeBadge_${{ github.ref_name }}-${{ matrix.platform }}${{ matrix.ext }}
          path: ./dist/target${{ matrix.ext }}
  release:
    runs-on: ubuntu-latest
    needs: release-target
    steps:
      - name: Fetching branch
        uses: actions/checkout@v3
      - name: Create builds directory
        run: mkdir builds
      - name: Download Linux build
        uses: actions/download-artifact@v3
        with:
          name: GiveMeBadge_${{ github.ref_name }}-linux
          path: builds/
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: GiveMeBadge_${{ github.ref_name }}-win32.exe
          path: builds/
      - name: Download macOS build
        uses: actions/download-artifact@v3
        with:
          name: GiveMeBadge_${{ github.ref_name }}-macos.bin
          path: builds/
      - name: Release prep
        run: |
          cd builds

          mv target "GiveMeBadge_${{ github.ref_name }}-linux"
          chmod +x *-linux

          sed -i "s/{{VERSION}}/${{ github.ref_name }}/g" ../assets/mac-app/Contents/Info.plist
          chmod +x target.bin
          mv target.bin ../assets/mac-app/Contents/MacOS/givemebadge
          cp -r ../assets/mac-app "GiveMeBadge_${{ github.ref_name }}-macos.app"
          zip -r "GiveMeBadge_${{ github.ref_name }}-macos.app.zip" *.app
          rm -rf *.app

          mv target.exe "GiveMeBadge_${{ github.ref_name }}-win64.exe"

          cd ..
          printf "\`SHA256\` Checksums:\n\`\`\`\n$(sha256sum builds/*)\n\`\`\`\n" > body.md
      - name: Release builds
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: GiveMeBadge ${{ github.ref_name }}
          files: builds/*
          body_path: body.md
